name: CI
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

env:
  REPO: ${{ github.event.repository.name }}
  REPO_ROOT: workspace/meta/core-products/${{ github.event.repository.name }}
  LINT_ROOT: workspace/meta/core-products/${{ github.event.repository.name }}
  PR_HEAD: ${{ github.event.pull_request.head.ref }}
  # Disable PHPCS for code lint until all files have been reformatted
  NO_PHPCS: 1

jobs:

  #==============#
  # 3. Run Tests #
  #==============#
  Test:
    if: "! contains(github.event.*.draft, true) && ! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    needs:
      - Lint
      - Build
    strategy:
      matrix:
        php:
          - php74
          - php56
        include:
          - php: php74
            phpver: 7.4.5
            wp: wp54
            os: ubuntu-20.04
          - php: php56
            phpver: 5.6.40
            wp: wp54
            os: ubuntu-20.04

    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    steps:
      #======================#
      # 3.1 Initialize Repos #
      #======================#
      - name: Maybe Change Environment Variables
        shell: bash
        run: exit 0
