name: CI
on: pull_request

jobs:

  #==============#
  # 3. Run Tests #
  #==============#
  Test:
    if: "! contains(github.event.*.draft, true) && ! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    strategy:
      matrix:
        php:
          - php74
          - php56
        include:
          - php: php74
            phpver: 7.4.5
            wp: wp54
            os: ubuntu-20.04
          - php: php56
            phpver: 5.6.40
            wp: wp54
            os: ubuntu-20.04

    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    steps:
      #======================#
      # 3.1 Initialize Repos #
      #======================#
      - name: Maybe Change Environment Variables
        shell: bash
        run: exit 0
