on: pull_request

name: Inspections
jobs:
  runPHPCSInspection:
    name: Run PHPCS inspection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current PR
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }} # 786d36d4d0dd876115619fcd886cb2fcd80cc3e3
          path: repo
#          token: ${{ secrets.ET_TOKEN }} # not needed on production but necessary for local tests.
#      - name: check contents
#        run: echo ${{ github.event.pull_request.head.sha }}
      - name: Checkout current phpcs rules
        uses: actions/checkout@v2
        with:
          repository: elegantthemes/marketplace-phpcs
          path: rules
          token: ${{ secrets.ET_TOKEN }}
      - id: goci
        name: Get latest release of vip-go-ci
        uses: pozetroninc/github-action-get-latest-release@v0.4.0
        with:
          repository: Automattic/vip-go-ci
      - name: Run Inspections
        uses: poxtron/ci-review@master
        env:
          GH_BOT_TOKEN: ${{ secrets.ET_TOKEN }}
          GOCI_VERSION: ${{ steps.goci.outputs.release }}
#      - name: check contents
#        run: echo ${{ github.event.pull_request.head.sha }}

